version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paris_opendata
      MYSQL_ROOT_HOST: "%"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my_root_password
      PMA_ARBITRARY: 0
    ports:
      - "8080:80"

volumes:
  db_data: